### ISSUE TITLE
So ... how did it go? :)

### ISSUE THREAD

**Issue by jedrichards** [matthew-andrews/npm-test-codeship-publish#1]
When googling for information about how to publish npm modules on CodeShip this repo comes near the top of the search results.

How did your test go? Did you get it working? I can't find much/any info.

I've got something working but it feels a bit hacky. Basically looks like this on CodeShip to login and then publish:

```
echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
npm publish
```

Did you manage anything more robust, or more idiomatic?

Thanks!

**Comment by matthew-andrews** [comment]
you probably don't want to do that…… it's a good way to leak your NPM credentials (which is what happened to me)……  i would honestly recommend using travis or something else that supports this natively :disappointed:

**Comment by matthew-andrews** [comment]
although your method seems safer than the approach i took…  i feel quite burnt stil

**Comment by jedrichards** [comment]
Those credentials are just in CodeShip's env var settings atm, i.e. not in source control or anything, so reasonably safe ... maybe?

**Comment by matthew-andrews** [comment]
yeah safer than my approach…

**Comment by jedrichards** [comment]
I just found this ... sounds like the recommended approach now. Generate an auth token, pop it into an env var, and reference it from an `.npmrc` file in the project root:

http://blog.npmjs.org/post/118393368555/deploying-with-npm-private-modules

**Comment by matthew-andrews** [comment]
there's a danger if you put it in the project root that you might accidentally publish that `.npmrc` in that package **onto** the npm registry.

**Comment by matthew-andrews** [comment]
(which would be bad)

**Comment by jedrichards** [comment]
As far as I understand it, that `.npmrc` just references the env var:

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

So there's no sensitive data in it, and it would only work if `NPM_TOKEN` was in the environment.

(Plus I think `.npmrc` are one of a set of filenames that are excluded from publishing by default)

**Comment by matthew-andrews** [comment]
NPM_TOKEN used to be just `username:password` base64'd …… Now it's proper key…… Less sensitive but still sensitive.

> (Plus I think .npmrc are one of a set of filenames that are excluded from publishing by default)

Yeah it is now but wasn't before…… so you need to be careful what version of npm is being run
